apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tebukuro
  labels:
    app: tebukuro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tebukuro
  template:
    metadata:
      labels:
        app: tebukuro
    spec:
      volumes:
      - name: web-sock
        emptyDir: {}
      containers:
        - image: $TEBUKURO_IMAGE
          name: tebukuro
          env:
            - name: RAILS_ENV
              value: "production"
            - name: DATABASE_HOST
              value: postgresql
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tebukuro
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tebukuro
                  key: database_password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: tebukuro
                  key: secret_key_base
            - name: DATABASE_PORT
              value: "5432"
            - name: GITHUB_KEY
              valueFrom:
                secretKeyRef:
                  name: tebukuro
                  key: github_key
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: tebukuro
                  key: github_secret
          ports:
            - containerPort: 3000
              name: tebukuro
          command: ["/app/script/wait.sh", "bundle", "exec", "rails", "s"]
          volumeMounts:
          - mountPath: /app/tmp/sockets
            name: web-sock
        - image: us.gcr.io/tebukuro-182304/nginx:0.0.1
          name: nginx
          ports:
          - name: http-server
            containerPort: 80
          - name: https-server
            containerPort: 443
          volumeMounts:
          - mountPath: /app/tmp/sockets
            name: web-sock
